package com.stochastictinkr.cards.standard

/**
 * A standard deck of 52 playing cards.
 */
data object StandardDeck {
    /**
     * The list of all 52 cards in a standard deck.
     * This is generated by combining each suit with each rank.
     * See [CardSuit] for the suit order and [CardRank] for the rank order.
     */
    val cards = CardSuit.entries.flatMap { suit ->
        CardRank.entries.map { rank ->
            Card(suit, rank)
        }
    }
}
